FROM golang:1.21 

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-gs-ping

#FROM scratch

#WORKDIR ./build

#COPY /docker-gs-ping ./

EXPOSE 8080

# Run
CMD ["/docker-gs-ping"]